In [ ]:
import pandas as pd
import numpy as np
import yfinance as yf

:

In [2]:
data = yf.download(tickers='BTC-USD', period='24h', interval='5m')
data

[*********************100%%**********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Datetime,,,,,,
2023-11-20 17:40:00+00:00,37428.730469,37431.082031,37363.175781,37370.125000,37370.125000,0
2023-11-20 17:45:00+00:00,37416.378906,37726.152344,37416.378906,37726.152344,37726.152344,244873216
2023-11-20 17:50:00+00:00,37700.316406,37756.820312,37693.671875,37693.671875,37693.671875,218808320
2023-11-20 17:55:00+00:00,37614.957031,37703.925781,37604.859375,37604.859375,37604.859375,233420800
2023-11-20 18:00:00+00:00,37599.191406,37683.562500,37595.574219,37661.328125,37661.328125,92934144
...,...,...,...,...,...,...
2023-11-21 17:20:00+00:00,37414.312500,37504.339844,37400.980469,37400.980469,37400.980469,216340480
2023-11-21 17:25:00+00:00,37399.187500,37424.222656,37347.957031,37347.957031,37347.957031,139358208
2023-11-21 17:30:00+00:00,37307.707031,37328.156250,37224.011719,37224.011719,37224.011719,0
2023-11-21 17:35:00+00:00,37169.886719,37169.886719,37017.886719,37017.886719,37017.886719,3452928
2023-11-21 17:40:00+00:00,37052.632812,37052.632812,37052.632812,37052.632812,37052.632812,0

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 289 entries, 2023-11-20 17:40:00+00:00 to 2023-11-21 17:40:00+00:00
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Open       289 non-null    float64
 1   High       289 non-null    float64
 2   Low        289 non-null    float64
 3   Close      289 non-null    float64
 4   Adj Close  289 non-null    float64
 5   Volume     289 non-null    int64
dtypes: float64(5), int64(1)
memory usage: 15.8 KB

In [4]:
data.to_csv('./data/bitcoin_data.csv')